name: devmarkaz
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^4.2.2

  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17

  shared_preferences: ^2.0.15
  provider: ^6.0.3

  extended_image: ^6.2.1
  lottie: ^1.4.1
  intl: ^0.17.0
  auto_size_text: ^3.0.0

  carousel_slider: ^4.1.1

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/icon.png"
  web:
    generate: true
    image_path: "assets/logos/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/gifs/
    - assets/jsons/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
